### ISSUE TITLE
copy and/or export

### ISSUE THREAD

**Issue by rcl4144** [JasonTitcomb/Discriminator#10]
I have Discriminator on 2 computers I use for programming and it's an AWESOME program and I have been using NC editors for over 30 years and you are the best...

Is there any way I can export a Scheme from one computer to another ie: export/import or copy/paste ??

Thank you,

Roger C Love
Owner/CEO
Reliable Consulting & Mfg., LLC

**Comment by JasonTitcomb** [comment]
I little late to respond I know but there is a share button in a few places.
Look in the upper right on the Scheme tab.

**Comment by rcl4144** [comment]
Thanks Jason….Better late than never….not a problem…Be Safe,…Roger..
