### ISSUE TITLE
license

### ISSUE THREAD

**Issue by Pharaun159** [JasonTitcomb/Discriminator#13]
I purchased about 5 or 6 years ago.  Been using it on some home hobby projects and now for a company.  Im trying to move my license to a new computer, but i cant for the life of my find the original transaction id.  Ive gone through numerous windows installations and hardware upgrades.  I also had my email i ise for stuff like this wiped when it hit 10k emails lol.  Any chance you can look it up and shoot me an email?

**Comment by JasonTitcomb** [comment]
Do you know what the email address was that you used?
Can't find Pharaun159 in the system.

**Comment by Pharaun159** [comment]
Yes.  Its under ***@***.***  Thank you very much

Sent from Yahoo Mail on Android 
 
  On Tue, Feb 8, 2022 at 7:20 AM, Jason ***@***.***> wrote:   


Do you know what the email address was that you used?
Can't find Pharaun159 in the system.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
