### ISSUE TITLE
This app can't run on your PC

### ISSUE THREAD

**Issue by tylerbd23** [JasonTitcomb/Discriminator#16]
I have registered and paid for a license number but when I try to open a file in Discriminator I get an error that reads.....
This App can't run on your PC. To find a version for your PC, check with the software publisher. How do I get discriminator to work?

**Comment by JasonTitcomb** [comment]
Sorry for the delay.
What is your operating system? Win10?
It does require DOT NET 4.5 or above.
You could try installing it manually.
https://www.microsoft.com/en-us/download/details.aspx?id=30653

It is "shareware". Anyone can download it an use it before paying for it.
I will gladly refund your money if you can't get it working.
