### ISSUE TITLE
Magen Not Working

### ISSUE THREAD

**Issue by TJamilTriple** [JasonTitcomb/Discriminator#20]
We our having problems with Macgen, when we try to run the program and start the .mor file we get an error. first, we get a popup that says problem with input file. then we get Path/File access errorln line# 0. It works on our other computers just fine but only with this one computer is doesn't want to work. it also doesn't remember the directory we were in when you relaunch the program. Any help on this would be appreciated. Thanks 
![1](https://github.com/JasonTitcomb/Discriminator/assets/139379238/1a33df40-0cc5-4592-a438-fd0144c3bcb2)
![2](https://github.com/JasonTitcomb/Discriminator/assets/139379238/7951a728-e573-4f06-a0fe-85b7267fa99b)

**Comment by JasonTitcomb** [comment]
Do you mean Discriminator CNC Editor?
I don't know what a .mor file is.

**Comment by TJamilTriple** [comment]
> Do you mean Discriminator CNC Editor? I don't know what a .mor file is.
No, so we have a program called MacGen. MacGen is an older program, it had a readme.txt which ill link here
[Readme.txt](https://github.com/JasonTitcomb/Discriminator/files/12171567/Readme.txt)
in the text file, 4 says for support email Sales@CNCedit.com so I went to cncedit.com to see if I could find direct contact info, and that's how I ended up at your GitHub. Based on your previous response, I'm assuming you don't know what MacGen is. So do u know anyone then I could contact to help? I've attached what the software looks like.
![3](https://github.com/JasonTitcomb/Discriminator/assets/139379238/0d362d3d-14b1-4b54-8fd7-37a252f11541)
MacGen is an application that visually shows a mill or lathe operator the tool path his program will run. Any help on this is very much appreciated so thank you for responding.

**Comment by JasonTitcomb** [comment]
Well I did write that, but it was 30 years ago or so.
It could be related to the path or file name. Try reading from a simple path like C:\Temp\.
Are you using it to generate Smart CAM macro code or just plot graphics?
You can use the free viewer for graphics.
https://www.cncedit.com/Basicviewer/
