### ISSUE TITLE
Toyoda FH450S Horizontal

### ISSUE THREAD

**Issue by wornmetal** [JasonTitcomb/Discriminator#23]
I work at VB Machine Works. I came across discriminator, and though it would be a great editor for our engineering department. the only thing I'm having issues with is it doesn't read G10 (programable data input). I was hoping you we be able to help me with this. 
Thx
Scott

Controls are Fanuc 15m, Fanuc 16m, and Fanuc 31i

**Comment by JasonTitcomb** [comment]
It should work.
There is a sample file. Please provide a simple sample.
![image](https://github.com/user-attachments/assets/b2aab099-49d2-46e5-95a4-bd78a411ff6e)
