### ISSUE TITLE
Find a text and replace with mutiple lines

### ISSUE THREAD

**Issue by Don92844** [JasonTitcomb/Discriminator#24]
Hi,
Can you create a function to find "M6" and replace as multiple lines as seen below?  In Note++, it will be M6 \nPRG20049999.
Thanks,
Don C.

N5 ; (.500EM X 1.25FL X .03R X 3FLTS YG1 [T-50092])
T83
M6 
T10

N5 ; (.500EM X 1.25FL X .03R X 3FLTS YG1 [T-50092])
T83
M6 
PRG20049999
T10

**Comment by JasonTitcomb** [comment]
How about adding a keyword to use the Windows Clipboard text as the replacement text?
![image](https://github.com/user-attachments/assets/0ed35dd2-207f-482f-8182-a3c163bfd6f3)

**Comment by JasonTitcomb** [comment]
This will be added to the .50 release
