### ISSUE TITLE
DXF Export

### ISSUE THREAD

**Issue by AJRimmer-SSC** [JasonTitcomb/Discriminator#27]
[8.8MM_DRILL.txt](https://github.com/user-attachments/files/17378837/8.8MM_DRILL.txt)

[HOLES.DXF.txt](https://github.com/user-attachments/files/17378846/HOLES.DXF.txt)

Odd artifacts in the DXF file. At the end location of each hole there an additional point that is .0006 away in X.

**Comment by JasonTitcomb** [comment]
I see.
Seems related to the rapid points indicators.
![image](https://github.com/user-attachments/assets/4a0d33cc-0419-4e02-9db7-586bc2a1997f)
Disable Rapid Points for now. The fix is in the next release.
