### ISSUE TITLE
Have my license number but I lost my transaction ID...How can I get it back ??

### ISSUE THREAD

**Issue by rcl4144** [JasonTitcomb/Discriminator#4]

**Comment by JasonTitcomb** [comment]
From within the program go to Help>License... menu.
On the License window click the Licensing web page link.
At that web page you can enter the email you used when you purchased.
When you submit it should find the transaction.

**Comment by rcl4144** [comment]
Thanks Jason for all your help much appreciated.  I have it all straightened out and working great....Reliable Consulting & Mfg., LLCRoger C love Owner/PresidentO: 928.476.1578C: 929.892.3570Sent from my smartphone...🤠
-------- Original message --------From: Jason Titcomb <notifications@github.com> Date: 5/30/20  4:11 AM  (GMT-07:00) To: JasonTitcomb/Discriminator <Discriminator@noreply.github.com> Cc: rcl4144 <reli.consult@gmail.com>, Author <author@noreply.github.com> Subject: Re: [JasonTitcomb/Discriminator] Have my license number but I lost my transaction ID...How can I get it back ?? (#4) 
Closed #4.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/JasonTitcomb/Discriminator/issues/4#event-3389635738",
"url": "https://github.com/JasonTitcomb/Discriminator/issues/4#event-3389635738",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
