### ISSUE TITLE
unexpected end before M30 or M99 2.1.0.59

### ISSUE THREAD

**Issue by GitBeagle** [JasonTitcomb/Discriminator#5]
I upgraded from 2.0.1.56 to 2.0.1.59 before committing to purchase your CNC tool. The earlier version worked great.  Now the viewer does not work.  I found the earlier issue where you suggested setting the SubEndMatch parameter. I found that parameter in the FAUNC_Parser.xml file. the parameter is set to M02|M99. The other files in the ParserSettings directory also have this same setting except the TurboCNC file has it set to M99|M02. 

I have a CNC router controlled by LinuxCNC. I use a couple different CAD/CAM programs to create the gcode. All of them show this same error when attempting to use the viewer.

**Comment by GitBeagle** [comment]
It appears closing the application and reopening it the following day "cured" my issue. Other than locating and opening the parser files I made no changes that I am aware of. In any case it seems my problem is solved or at least has disappeared.

Sorry for any confusion.

**Comment by JasonTitcomb** [comment]
Thanks for reporting
